package com.github.no_name_provided.nnp_rune_smithing.datagen.providers;

import com.github.no_name_provided.nnp_rune_smithing.common.items.CastingTemplate;
import com.github.no_name_provided.nnp_rune_smithing.common.items.RSItems;
import com.github.no_name_provided.nnp_rune_smithing.datagen.providers.subproviders.global_loot_modifiers.SingleItemPools;
import net.minecraft.advancements.critereon.BlockPredicate;
import net.minecraft.advancements.critereon.LocationPredicate;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.levelgen.structure.BuiltinStructures;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.predicates.LocationCheck;
import net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemEntityPropertyCondition;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.GlobalLootModifierProvider;
import net.neoforged.neoforge.common.loot.AddTableLootModifier;
import net.neoforged.neoforge.common.loot.LootTableIdCondition;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.concurrent.CompletableFuture;

import static com.github.no_name_provided.nnp_rune_smithing.NNPRuneSmithing.MODID;

public class GlobalLootModifiers extends GlobalLootModifierProvider {
    public GlobalLootModifiers(PackOutput output, CompletableFuture<HolderLookup.Provider> registries) {
        super(output, registries, MODID);
    }
    
    /**
     * Call {@link #add} here, which will pass in the necessary information to write the jsons.
     */
    @Override
    protected void start() {
        createSimpleAdditionByID("self_template_pyramid", BuiltInLootTables.DESERT_PYRAMID.location(), RSItems.SELF_TEMPLATE, 10);
        createSimpleAdditionByID("collision_template_jungle_temple", BuiltInLootTables.JUNGLE_TEMPLE.location(), RSItems.COLLISION_TEMPLATE);
        createSimpleChestAdditionByStructure("wield_template_mineshaft", BuiltinStructures.MINESHAFT, RSItems.WIELD_TEMPLATE, 10);
        createSimpleAdditionByID("water_template_buried_treasure", BuiltInLootTables.BURIED_TREASURE.location(), RSItems.WATER_TEMPLATE);
        createSimpleAdditionByID("earth_template_stronghold_library", BuiltInLootTables.STRONGHOLD_LIBRARY.location(), RSItems.EARTH_TEMPLATE, 10);
        createSimpleAdditionByID("fire_template_bastion_treasure", BuiltInLootTables.BASTION_TREASURE.location(), RSItems.FIRE_TEMPLATE, 10);
        createSimpleAdditionByID("air_template_pillager_outpost", BuiltInLootTables.PILLAGER_OUTPOST.location(), RSItems.AIR_TEMPLATE, 10);
        createSimpleAdditionByID("ward_template_woodland_mansion", BuiltInLootTables.WOODLAND_MANSION.location(), RSItems.WARD_TEMPLATE, 10);
        createSimpleChestAdditionByStructure("widen_rune_fortress", BuiltinStructures.FORTRESS, RSItems.WIDEN_TEMPLATE, 10);
        createSimpleAdditionByID("amplify_template_end_treasure", BuiltInLootTables.END_CITY_TREASURE.location(), RSItems.AMPLIFY_TEMPLATE, 10);
    }
    
    /**
     * Item must already have appropriately named loot table generated by another subprovider.
     */
    void createSimpleAdditionByID(String name, ResourceLocation lootTableID, DeferredHolder<Item, CastingTemplate> item, int reciprocalOfOdds) {
        add(
                name,
                new AddTableLootModifier(
                        new LootItemCondition[]{
                                LootTableIdCondition.builder(
                                        lootTableID
                                ).build()
                        },
                        SingleItemPools.getTemplateKey(item, reciprocalOfOdds)
                )
        );
    }
    
    void createSimpleAdditionByID(String name, ResourceLocation lootTableID, DeferredHolder<Item, CastingTemplate> item) {
        this.createSimpleAdditionByID(name, lootTableID, item, 1);
    }
    
    void createSimpleChestAdditionByStructure(String name, ResourceKey<Structure> structure, DeferredHolder<Item, CastingTemplate> item, int reciprocalOfOdds) {
        add(
                name,
                new AddTableLootModifier(
                        new LootItemCondition[]{
                                LocationCheck.checkLocation(LocationPredicate.Builder.inStructure(
                                            registries.lookupOrThrow(Registries.STRUCTURE).getOrThrow(structure)
                                        ).setBlock(
                                                BlockPredicate.Builder.block().of(Tags.Blocks.CHESTS)
                                        )
                                ).build()
                        },
                        SingleItemPools.getTemplateKey(item, reciprocalOfOdds)
                )
        );
    }
}