package com.github.no_name_provided.nnp_rune_smithing.datagen.providers;

import com.github.no_name_provided.nnp_rune_smithing.common.items.CastingTemplate;
import com.github.no_name_provided.nnp_rune_smithing.common.items.RSItems;
import com.github.no_name_provided.nnp_rune_smithing.datagen.providers.subproviders.global_loot_modifiers.SingleItemPools;
import net.minecraft.advancements.critereon.LocationPredicate;
import net.minecraft.core.BlockPos;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.levelgen.structure.BuiltinStructures;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.storage.loot.predicates.LocationCheck;
import net.neoforged.neoforge.common.data.GlobalLootModifierProvider;
import net.neoforged.neoforge.common.loot.AddTableLootModifier;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import static com.github.no_name_provided.nnp_rune_smithing.NNPRuneSmithing.MODID;

public class GlobalLootModifiers extends GlobalLootModifierProvider {
    public GlobalLootModifiers(PackOutput output, CompletableFuture<HolderLookup.Provider> registries) {
        super(output, registries, MODID);
    }
    
    /**
     * Call {@link #add} here, which will pass in the necessary information to write the jsons.
     */
    @Override
    protected void start() {
        createSimpleStructureAddition("self_template_pyramid", BuiltinStructures.DESERT_PYRAMID, RSItems.SELF_TEMPLATE, 10);
        createSimpleStructureAddition("collision_template_jungle_temple", BuiltinStructures.JUNGLE_TEMPLE, RSItems.COLLISION_TEMPLATE);
        createSimpleStructureAddition("wield_template_swamp_hut", BuiltinStructures.SWAMP_HUT, RSItems.WIELD_TEMPLATE, 10);
        createSimpleStructureAddition("water_template_buried_treasure", BuiltinStructures.BURIED_TREASURE, RSItems.WATER_TEMPLATE);
        createSimpleStructureAddition("earth_template_stronghold", BuiltinStructures.STRONGHOLD, RSItems.EARTH_TEMPLATE, 10);
        createSimpleStructureAddition("fire_template_bastion_remnant", BuiltinStructures.BASTION_REMNANT, RSItems.FIRE_TEMPLATE, 10);
        createSimpleStructureAddition("air_template_pillager_outpost", BuiltinStructures.PILLAGER_OUTPOST, RSItems.AIR_TEMPLATE, 10);
        createSimpleStructureAddition("ward_template_woodland_mansion", BuiltinStructures.WOODLAND_MANSION, RSItems.WARD_TEMPLATE, 10);
        createSimpleStructureAddition("widen_rune_fortress", BuiltinStructures.FORTRESS, RSItems.WIDEN_TEMPLATE, 10);
        createSimpleStructureAddition("amplify_template_end_city", BuiltinStructures.END_CITY, RSItems.AMPLIFY_TEMPLATE, 10);
    }
    
    /**
     * Item must already have appropriately named loot table generated by another subprovider.
     */
    void createSimpleStructureAddition(String name, ResourceKey<Structure> structure, DeferredHolder<Item, CastingTemplate> item, int reciprocalOfOdds) {
        add(
                name,
                new AddTableLootModifier(
                        new LocationCheck[]{
                                new LocationCheck(
                                        Optional.of(LocationPredicate.Builder.inStructure(
                                                registries.lookupOrThrow(Registries.STRUCTURE
                                                ).getOrThrow(structure)).build()),
                                        BlockPos.ZERO
                                )},
                        SingleItemPools.getTemplateKey(item, reciprocalOfOdds)
                )
        );
    }
    
    void createSimpleStructureAddition(String name, ResourceKey<Structure> structure, DeferredHolder<Item, CastingTemplate> item) {
        createSimpleStructureAddition(name, structure, item, 1);
    }
}