package com.github.no_name_provided.nnp_rune_smithing.datagen.providers;

import com.github.no_name_provided.nnp_rune_smithing.client.particles.RSParticleTypes;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.common.data.ParticleDescriptionProvider;

import static com.github.no_name_provided.nnp_rune_smithing.NNPRuneSmithing.MODID;

public class RSParticleDescriptionProvider extends ParticleDescriptionProvider {
    /**
     * Creates an instance of the data provider.
     *
     * @param output     the expected root directory the data generator outputs to
     * @param fileHelper the helper used to validate a texture's existence
     */
    public RSParticleDescriptionProvider(PackOutput output, ExistingFileHelper fileHelper) {
        super(output, fileHelper);
    }
    
    /**
     * Registers the particle descriptions generated by {@link #sprite(ParticleType, ResourceLocation)} or one of the
     * {@link #spriteSet(ParticleType, Iterable) sprite set methods}.
     */
    @Override
    protected void addDescriptions() {
        spriteSet(
                RSParticleTypes.SELF_RUNE.get(),
                ResourceLocation.fromNamespaceAndPath(MODID, "self_rune"),
                3,
                false
        );
        spriteSet(
                RSParticleTypes.WIELD_RUNE.get(),
                ResourceLocation.fromNamespaceAndPath(MODID, "wield_rune"),
                3,
                false
        );
        spriteSet(
                RSParticleTypes.COLLISION_RUNE.get(),
                ResourceLocation.fromNamespaceAndPath(MODID, "collision_rune"),
                3,
                false
        );
    }
}
