@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.github.no_name_provided.nnp_rune_smithing.datagen.loot_conditions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;