@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.github.no_name_provided.nnp_rune_smithing.common.advancements;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;