@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.github.no_name_provided.nnp_rune_smithing.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;